---
- name:  Serveur Setup
  hosts: all
  remote_user: root
  tasks:
  - include_vars:
      file: vars/vars.yml
  - name: "USER | Creation : {{ user }}"
    user: 
      name: "{{ user }}"
      shell: /bin/bash
  - name: USER | Clef SSH
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

  - name: APT | Update & Upgrade
    apt:
      upgrade: dist
      update_cache: yes
  - include_role:
      name: tools
  - include_role:
      name: php
  - include_role:
      name: mysql
  - include_role:
      name: nginx